#!/usr/bin/env node
/**
 * extract_cookies_playwright.js ??? Extract YouTube cookies via Playwright.
 * Supports CDP connect (YTL_CDP_URL env) and fresh launch mode.
 */
const fs = require('fs');
const path = require('path');
const os = require('os');

const BROWSER = (process.argv[2] || 'edge').toLowerCase();
const OUTPUT = process.argv[3] || 'cookies.txt';
const HEADLESS = process.env.YTL_HEADLESS === '1';
const CDP_URL = process.env.YTL_CDP_URL || null;
const PROFILE_DIR = process.env.YTL_PROFILE_DIR || null;

console.log('======================================================');
console.log('  Cookie Extractor (Playwright)');
console.log('======================================================');
console.log(`Browser:  ${BROWSER}`);
console.log(`Output:   ${OUTPUT}`);
console.log(`CDP URL:  ${CDP_URL || '(fresh launch mode)'}`);
console.log(`Profile:  ${PROFILE_DIR || '(default)'}`);
console.log('');

let playwright;
try { playwright = require('playwright'); }
catch (e) { console.error('??? Playwright not installed'); process.exit(1); }

function findEdgePath() {
    const cands = process.platform === 'win32'
        ? [
            'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
            'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
        ]
        : process.platform === 'darwin'
            ? ['/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge']
            : ['/usr/bin/microsoft-edge', '/usr/bin/microsoft-edge-stable'];
    for (const p of cands) if (fs.existsSync(p)) return p;
    return null;
}

const YOUTUBE_DOMAINS = ['youtube.com','google.com','accounts.google.com','m.youtube.com'];

function isYoutubeDomain(domain) {
    if (!domain) return false;
    const d = domain.toLowerCase().replace(/^\./, '');
    return YOUTUBE_DOMAINS.some(yt => d === yt || d.endsWith('.' + yt));
}

function toNetscapeLine(cookie) {
    const domain = cookie.domain || '';
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path_ = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.expires && cookie.expires > 0 ? Math.floor(cookie.expires) : 0;
    const name = String(cookie.name || '').replace(/\t/g, '\\t').replace(/\n/g, '\\n');
    const value = String(cookie.value || '').replace(/\t/g, '\\t').replace(/\n/g, '\\n');
    return `${domain}\t${flag}\t${path_}\t${secure}\t${expires}\t${name}\t${value}`;
}

function writeCookies(cookies, outputPath) {
    const header = [
        '# Netscape HTTP Cookie File',
        `# Generated by extract_cookies_playwright.js on ${new Date().toISOString()}`,
        '# https://curl.se/docs/http-cookies.html',
        '#',
        '',
    ].join('\n');
    const lines = cookies.map(toNetscapeLine);
    fs.writeFileSync(outputPath, header + lines.join('\n') + '\n', 'utf8');
    console.log(`??? Wrote ${cookies.length} cookies to: ${outputPath}`);
}

function verifyCritical(cookies) {
    const critical = ['SID','SSID','HSID','APISID','SAPISID','LOGIN_INFO','VISITOR_INFO1_LIVE','__Secure-3PSID'];
    const names = new Set(cookies.map(c => c.name));
    console.log('');
    console.log('Critical YouTube cookies check:');
    let allOk = true;
    for (const name of critical) {
        if (names.has(name)) { console.log(`  ??? ${name}`); }
        else { console.log(`  ??? ${name} MISSING`); allOk = false; }
    }
    return allOk;
}

(async () => {
    let context, cdpBrowser;

    if (CDP_URL) {
        console.log(`Connecting to CDP: ${CDP_URL}`);
        try {
            cdpBrowser = await playwright.chromium.connectOverCDP(CDP_URL);
            context = cdpBrowser.contexts()[0];
            if (!context) throw new Error('No existing context');
            console.log('??? Connected to running Edge via CDP');
        } catch (e) {
            console.error(`??? CDP connect failed: ${e.message}`);
            process.exit(1);
        }
    } else {
        const edgePath = findEdgePath();
        if (!edgePath) { console.error('??? Edge not found'); process.exit(1); }
        const profile = PROFILE_DIR || path.join(os.homedir(), 'EdgeDebugProfile');
        console.log(`Launching Edge with profile: ${profile}`);
        try {
            context = await playwright.chromium.launchPersistentContext(profile, {
                executablePath: edgePath,
                channel: 'msedge',
                headless: HEADLESS,
                viewport: { width: 1280, height: 800 },
                args: ['--disable-blink-features=AutomationControlled','--no-first-run','--no-default-browser-check'],
            });
        } catch (e) {
            console.error(`??? Launch failed: ${e.message}`);
            process.exit(1);
        }
    }

    try {
        const page = await context.newPage();
        console.log('Navigating to YouTube...');
        await page.goto('https://www.youtube.com', { waitUntil: 'domcontentloaded', timeout: 45000 });

        const signedIn = await page.evaluate(() => {
            return !!(document.querySelector('#avatar-btn') ||
                     document.querySelector('button[aria-label*="Account"]'));
        }).catch(() => false);

        if (!signedIn) {
            console.log('');
            console.log('??????  NOT SIGNED IN');
            console.log('   You have 120 seconds to sign into YouTube in the browser window.');
            console.log('');
            const start = Date.now();
            while (Date.now() - start < 120000) {
                await page.waitForTimeout(3000);
                const now = await page.evaluate(() => {
                    return !!(document.querySelector('#avatar-btn') ||
                             document.querySelector('button[aria-label*="Account"]'));
                }).catch(() => false);
                if (now) { console.log('??? Sign-in detected'); break; }
            }
        } else {
            console.log('??? Already signed in');
        }

        console.log('Visiting a YouTube video...');
        try { await page.goto('https://www.youtube.com/watch?v=dQw4w9WgXcQ', { waitUntil: 'domcontentloaded', timeout: 45000 }); } catch {}
        await page.waitForTimeout(5000);

        const allCookies = await context.cookies();
        const yt = allCookies.filter(c => isYoutubeDomain(c.domain));
        console.log(`Total cookies: ${allCookies.length}`);
        console.log(`YouTube/Google: ${yt.length}`);

        if (yt.length === 0) { console.error('??? No YouTube cookies'); process.exit(1); }

        writeCookies(yt, OUTPUT);
        const ok = verifyCritical(yt);

        if (cdpBrowser) { try { await cdpBrowser.close(); } catch {} }
        else if (context) { try { await context.close(); } catch {} }
        process.exit(ok ? 0 : 1);
    } catch (e) {
        console.error(`??? Error: ${e.message}`);
        try { if (cdpBrowser) await cdpBrowser.close(); else if (context) await context.close(); } catch {}
        process.exit(1);
    }
})();
