/**
 * cleanup-orphans.js — removes orphan video entries from the DB.
 *
 * An "orphan" is a video whose id starts with "disk_" (auto-generated by
 * Update DB when no video ID could be matched) AND whose finalFilename
 * starts with "ytl_" (never got properly renamed).
 *
 * These entries can never be matched to a real YouTube video or disk file,
 * so they just show as phantom rows in the UI.
 */

const path = require('path');
const Database = require('better-sqlite3');

const DB_PATH = path.join(__dirname, 'database.db');
const db = new Database(DB_PATH);

console.log('Opening:', DB_PATH);
console.log('');

// Find orphans: id starts with 'disk_' AND finalFilename starts with 'ytl_'
const orphans = db.prepare(`
    SELECT id, channelId, title, finalFilename, filePath
    FROM videos
    WHERE id LIKE 'disk_%'
       OR (finalFilename LIKE 'ytl_%' AND id LIKE 'disk_%')
`).all();

console.log(`Found ${orphans.length} orphan entries:\n`);
orphans.forEach(v => {
    console.log(`  id:        ${v.id}`);
    console.log(`  channelId: ${v.channelId}`);
    console.log(`  title:     ${v.title}`);
    console.log(`  filename:  ${v.finalFilename}`);
    console.log('');
});

if (orphans.length === 0) {
    console.log('✅ No orphans to clean up.');
    db.close();
    process.exit(0);
}

// Delete them
const ids = orphans.map(v => v.id);
const placeholders = ids.map(() => '?').join(',');

const result = db.prepare(`DELETE FROM videos WHERE id IN (${placeholders})`).run(...ids);

console.log(`✅ Deleted ${result.changes} orphan entries.`);

// Verify
const remaining = db.prepare(`
    SELECT COUNT(*) AS n FROM videos WHERE id LIKE 'disk_%'
`).get().n;

console.log(`Remaining disk_ entries: ${remaining}`);

db.close();
console.log('');
console.log('Restart the server, then reload the browser.');